<?php 
// Para volver a la vista
function comment_comeback_form_comment_form_alter(&$form, &$form_state, $form_id){
$form['#submit'][] = 'pedro';
}


function pedro($form, &$form_state) {
//$form_state['redirect'] = '';
$http_host = "http://" . $_SERVER['HTTP_HOST'] . "/";
$http_referer = str_replace($http_host, $_SERVER['HTTP_REFERER']);
$destination = parse_url($http_referer);
$form_state['redirect'] = $destination;
}
